### ISSUE TITLE
Signing images with cosign fails with KDF error

### ISSUE THREAD

**Issue by ThomasVitale** [buildpacks-community/kpack#1322] opened 2023-09-08 21:55 UTC
**What happened**

When using kpack to sign the built images with Cosign, the signing step fails if the key pair has been created with the Cosing CLI 2.2.0 (the latest version at the moment). It works when using the previous version of the CLI (2.1.1).

I can see there's an open Dependabot PR (#1318) to update the Cosign version to 2.2.0 (the latest one). I assume the defect would be fixed by updating the Cosign dependencies in that pull request.

**Logs**

This is the error log I get from the kpack build.

`cosign sign: unable to sign image with /var/build-secrets/cosign/supply-chain-cosign-key-pair/cosign.key: getting signer: reading key: decrypt: encrypted: unexpected kdf parameters`

**Versions**

I tried both using the latest kpack version (0.12.0) and the previous one (0.11.2). Same result.

**Comment by chenbh** [comment] 2023-09-11 19:57
Root cause is that the keys generated by Cosign v2.2.0 has a [higher default scrypt iteration count](https://github.com/secure-systems-lab/go-securesystemslib/blob/v0.7.0/encrypted/encrypted.go#L50-L54) than what Cosign v2.1.1 [supported](https://github.com/theupdateframework/go-tuf/blob/v0.5.2/encrypted/encrypted.go#L26-L33). 

The PR that did this is https://github.com/sigstore/cosign/pull/3183, but the actual discussion occurred in https://github.com/sigstore/cosign/pull/3128. Bit of a bummer that it wasn't called out in the release notes, but yeah a dependency bump will fix this issue.

**Comment by ThomasVitale** [comment] 2023-09-12 08:03
@chenbh thanks for the information. I've been trying to find the root cause, but couldn't find anything in the release notes and related issues. Now I see why. It's unfortunate to have such a breaking change in a minor upgrade without info.

I can see the PR upgrading cosign in kpack is now green: https://github.com/buildpacks-community/kpack/pull/1318. Once it's merged, I guess we can close this issue.

**Comment by chenbh** [comment] 2023-09-20 20:24
[v0.12.1](https://github.com/buildpacks-community/kpack/releases/tag/v0.12.1) released with the fix

**Closed by chenbh** 2023-09-20 20:24 UTC
